export const ADD_TOPIC = "ADD_TOPIC";
export const DELETE_TOPIC = "DELETE_TOPIC";
export const TOGGLE_TOPIC = "TOGGLE_TOPIC";
export const REQUEST_TOPICS = "REQUEST_TOPIC";
export const RECIEVE_TOPICS = "RECIEVE_TOPIC";
export const ADD_WEBSITE = "ADD_WEBSITE";
export const DELETE_WEBSITE = "DELETE_WEBSITE";
export const TOGGLE_WEBSITE = "TOGGLE_WEBSITE";
